### ISSUE TITLE
Sec -> msec

### ISSUE THREAD

**Issue by dedok** [dedok/nginx-stat-module#3]

**Comment by isgondurasa** [comment]
influx supports nanoseconds by default.

So there are two ways to solve this issue:
* sec -> nanosec
note: don't multiply ngx_time() on N to get nanoseconds before evaluation . 
We should only change timestamp right before UDP request

* change influxdb settings
influxdb.conf contains set of UDP settings. There is parameter called precision.
just put the line below under UDP settings in the influxdb.conf file
```
precision="s"
```
it works

**Comment by dedok** [comment]
@isgondurasa thanks for the patch.
